// Infring Chat Page — Agent chat with markdown + streaming
'use strict';

function chatPage() {
  var msgId = 0;
  return {
    currentAgent: null,
    systemThreadId: 'system',
    systemThreadName: 'System',
    systemThreadEmoji: '\u2699\ufe0f',
    systemTerminalSessionId: '',
    messages: [],
    inputText: '',
    chatInputHistory: [],
    terminalInputHistory: [],
    chatInputHistoryCursor: -1,
    terminalInputHistoryCursor: -1,
    chatInputHistoryDraft: '',
    terminalInputHistoryDraft: '',
    inputHistoryMaxEntries: 500,
    inputHistoryCacheKey: 'infring-chat-input-history-v1',
    inputHistorySessionScopePrefix: 'session:',
    _inputHistoryByAgent: {},
    _inputHistoryApplying: false,
    sending: false,
    messageQueue: [],    // Queue for messages sent while streaming
    promptQueueDragId: '',
    _promptQueueSeq: 0,
    thinkingMode: 'off', // 'off' | 'on' | 'stream'
    _wsAgent: null,
    showAttachMenu: false,
    attachPickerSessionActive: false,
    attachPickerRestoreMode: 'send',
    _attachPickerFocusListener: null,
    _attachPickerFocusTimer: 0,
    showSlashMenu: false,
    slashFilter: '',
    slashIdx: 0,
    slashAliasMap: {},
    slashAliasStorageKey: 'infring-chat-slash-aliases-v1',
    agentRuntimeSlashCommandProjection: null,
    agentRuntimeSlashCommandRows: [],
    _agentRuntimeSlashCommandProjectionAt: 0,
    _agentRuntimeSlashCommandProjectionEngineId: '',
    _agentRuntimeSlashCommandProjectionLoading: false,
    slashCommandFeedback: null,
    _slashCommandFeedbackTimer: 0,
    attachments: [],
    pasteToMarkdownEnabled: true,
    pasteToMarkdownCharThreshold: 2000,
    pasteToMarkdownLineThreshold: 40,
    dragOver: false,
    contextPressure: 'low',
    contextWindow: 8192,
    contextApproxTokens: 0,
    terminalMode: false,
    terminalCwd: '/workspace',
    terminalShortcutHint: 'Ctrl+\\',
    terminalCursorFocused: false,
    terminalSelectionStart: 0,
    _contextTelemetryTimer: null,
    _telemetryAlertsTimer: null,
    _lastTelemetryAlertDigest: '',
    telemetryNextActions: [],
    _telemetrySnapshot: null,
    _lastContextRequestAt: 0,
    _contextWindowByModel: {},
    _contextModelsFetchedAt: 0,
    _typingTimeout: null,
    // Multi-session state
    sessions: [],
    sessionsOpen: false,
    searchOpen: false,
    searchQuery: '',
    messageDisplayInitialLimit: 10,
    messageDisplayStep: 5,
    messageDisplayCount: 10,
    messageTextRenderWindowRadius: 20,
    _messageDisplayKey: '',
    // Voice recording state
    recording: false,
    _mediaRecorder: null,
    _audioChunks: [],
    recordingTime: 0,
    _recordingTimer: null,
    // Model autocomplete state
    showModelPicker: false,
    modelPickerList: [],
    modelPickerFilter: '',
    modelPickerIdx: 0,
    // Model switcher dropdown
    showModelSwitcher: false,
    modelSwitcherFilter: '',
    modelSwitcherProviderFilter: '',
    modelSwitcherIdx: 0,
    showRuntimeSwitcher: false,
    runtimeEngineRows: [],
    runtimeEngineLoading: false,
    runtimeEngineError: '',
    runtimeEngineCacheTime: 0,
    activeWorkspaceProjection: null,
    activeWorkspaceLoading: false,
    activeWorkspacePicking: false,
    activeWorkspaceError: '',
    activeWorkspaceCacheTime: 0,
    selectedAgentRuntimeEngineId: 'infring_native',
    agentRuntimeEngineStorageKey: 'infring-selected-agent-runtime-engine-v1',
    agentRuntimePermissionPolicyStorageKey: 'infring-agent-runtime-permission-policy-v1',
    agentRuntimePermissionPolicy: null,
    pendingAgentRuntimePermissionRequests: [],
    showGitTreeMenu: false,
    gitTreeMenuLoading: false,
    gitTreeMenuError: '',
    gitTreeMenuItems: [],
    gitTreeSwitching: false,
    modelApiKeyInput: '',
    modelApiKeySaving: false,
    modelApiKeyStatus: '',
    modelDownloadBusy: {},
    modelDownloadProgress: {},
    _modelDownloadProgressTimers: {},
    modelSwitching: false,
    _modelCache: null,
    _modelCacheTime: 0,
    _modelLogoFailIndex: {},
    _modelSourceLogoFailIndex: {},
    _modelSwitcherViewCache: null,
    _chatMapWheelLockInstalled: false,
    sessionLoading: false,
    _sessionLoadSeq: 0,
    _hasMoreMessages: false,
    _messagePageOffset: 0,
    _olderMessagesLoading: false,
    toolPreviewMaxLines: 2,
    toolPreviewMaxChars: 100,
    messageHydration: {},
    messageHydrationReady: false,
    _forcedHydrateById: {},
    _renderWindowRaf: 0,
    showFreshArchetypeTiles: false,
    freshInitTemplateDef: null,
    freshInitTemplateName: '',
    freshInitName: '',
    freshInitEmoji: '',
    freshInitDefaultName: '',
    freshInitDefaultEmoji: '',
    freshInitLaunching: false,
    freshInitRevealMenu: false,
    freshInitStageToken: 0,
    freshInitAvatarUrl: '',
    freshInitAvatarUploading: false,
    freshInitAvatarUploadError: '',
    freshInitEmojiPickerOpen: false,
    freshInitEmojiSearch: '',
    freshInitOtherPrompt: '',
    freshInitAwaitingOtherPrompt: false,
    freshInitPersonalityId: 'none',
    freshInitLifespanId: '1h',
    freshInitAdvancedOpen: false,
    freshInitVibeId: 'none',
    freshInitModelSuggestions: [],
    freshInitModelSelection: '',
    freshInitModelManual: false,
    freshInitModelSuggestLoading: false,
    freshInitPermissionOverrides: {},
    freshInitPermissionCatalog: [
      { category: 'web', name: 'Web', permissions: [
        { key: 'web.search.basic', label: 'Basic web search', default_checked: true },
        { key: 'web.fetch.url', label: 'Fetch URL content', default_checked: false }
      ]},
      { category: 'agent', name: 'Agent', permissions: [
        { key: 'agent.spawn', label: 'Spawn child agents', default_checked: false },
        { key: 'agent.permissions.manage', label: 'Manage permissions', default_checked: false }
      ]},
      { category: 'file', name: 'File', permissions: [
        { key: 'file.read.workspace', label: 'Read workspace files', default_checked: false },
        { key: 'file.write.workspace', label: 'Write workspace files', default_checked: false },
        { key: 'file.delete.workspace', label: 'Delete workspace files', default_checked: false }
      ]},
      { category: 'github', name: 'GitHub', permissions: [
        { key: 'github.issue.create', label: 'Create GitHub issues', default_checked: false }
      ]},
      { category: 'terminal', name: 'Terminal', permissions: [
        { key: 'terminal.exec', label: 'Execute terminal commands', default_checked: false }
      ]},
      { category: 'memory', name: 'Memory', permissions: [
        { key: 'memory.write', label: 'Write durable memory', default_checked: false }
      ]}
    ],
    conversationCache: {},
    conversationCacheKey: 'of-chat-conversation-cache-v1',
    conversationCacheVersionKey: 'of-chat-conversation-cache-version',
    conversationCacheVersion: 'v3-preview-projection-20260515',
    messageLineExpandState: {},
    messageLineExpandStep: 20,
    _persistTimer: null,
    _responseStartedAt: 0,
    typingWordCadenceMs: 1,
    _pointerGridHideTimer: null,
    _pointerTrailMouseHeld: false,
    _pointerTrailHoldHost: null,
    _pointerTrailMouseUpHandler: null,
    _pendingAutoModelSwitchBaseline: '',
    _pendingWsRequest: null,
    _pendingWsRecovering: false,
    _wsConnectSeq: 0,
    _inflightPayload: null,
    _inflightFailoverInProgress: false,
    _sendWatchdogTimer: null,
    _continuitySnapshot: null,
    _hoverClearTimer: 0,
    modelNoticeCache: {},
    modelNoticeCacheKey: 'of-chat-model-notices-v1',
    modelUsageCache: {},
    modelUsageCacheKey: 'of-chat-model-usage-v1',
    showScrollDown: false,
    scrollBottomBufferPx: 84,
    scrollBottomFollowTolerancePx: 32,
    scrollBottomClampSlackPx: 16,
    _stickToBottom: true,
    hoveredMessageDomId: '',
    directHoveredMessageDomId: '',
    selectedMessageDomId: '',
    _systemMessageDedupeIndex: {},
    mapStepIndex: -1,
    suppressMapPreview: false,
    _mapPreviewSuppressTimer: null,
    _scrollSyncFrame: 0,
    _bottomClampTimer: 0,
    _lastMessagesScrollAt: 0,
    _openPinToken: 0,
    _openPinRaf: 0,
    _openPinTimer: 0,
    _lastPointerClientX: 0,
    _lastPointerClientY: 0,
    _lastInactiveNoticeKey: '',
    _agentMissingSince: 0,
    _agentMissingAgentId: '',
    _agentMissingGraceMs: 12000,
    collapsedMessageDays: {},
    showAgentDrawer: false,
    agentDrawerLoading: false,
    agentDrawer: null,
    drawerTab: 'info',
    drawerConfigForm: {},
    drawerConfigSaving: false,
    drawerModelSaving: false,
    drawerIdentitySaving: false,
    drawerSavePending: false,
    drawerEditingModel: false,
    drawerEditingProvider: false,
    drawerEditingFallback: false,
    drawerEditingName: false,
    drawerEditingEmoji: false,
    drawerEmojiPickerOpen: false,
    drawerEmojiSearch: '',
    drawerAvatarUrlPickerOpen: false,
    drawerAvatarUrlDraft: '',
    drawerAvatarUploading: false,
    drawerAvatarUploadError: '',
    drawerNewModelValue: '',
    drawerNewProviderValue: '',
    drawerNewFallbackValue: '',
    drawerEmojiCatalog: [
      { emoji: '🤖', name: 'robot' },
      { emoji: '🧠', name: 'brain' },
      { emoji: '🧑\u200d💻', name: 'developer' },
      { emoji: '🛠️', name: 'tools' },
      { emoji: '🔬', name: 'research' },
      { emoji: '🧪', name: 'experiment' },
      { emoji: '🛰️', name: 'signal' },
      { emoji: '📡', name: 'telemetry' },
      { emoji: '🚀', name: 'launch' },
      { emoji: '🧭', name: 'navigator' },
      { emoji: '🦾', name: 'strong arm' },
      { emoji: '🔐', name: 'security' },
      { emoji: '🛡️', name: 'shield' },
      { emoji: '📈', name: 'growth' },
      { emoji: '📊', name: 'analytics' },
      { emoji: '📝', name: 'writer' },
      { emoji: '🎯', name: 'target' },
      { emoji: '💡', name: 'idea' },
      { emoji: '🌐', name: 'network' },
      { emoji: '🧱', name: 'builder' },
      { emoji: '🧰', name: 'toolbox' },
      { emoji: '🦉', name: 'wise owl' },
      { emoji: '🔥', name: 'fire' }
    ],
    drawerArchetypeOptions: ['Assistant', 'Researcher', 'Coder', 'Writer', 'DevOps', 'Support', 'Analyst', 'Custom'],
    drawerVibeOptions: ['professional', 'friendly', 'technical', 'creative', 'concise', 'mentor'],
    chatArchetypeTemplates: [
      {
        name: 'General Assistant',
        category: 'General',
        description: 'Versatile helper for everyday tasks and recommendations.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'full',
        archetype: 'assistant',
        system_prompt: 'You are a helpful, friendly assistant. Provide clear, accurate, and concise responses. Ask clarifying questions when needed.'
      },
      {
        name: 'Code Helper',
        category: 'Development',
        description: 'Programming-focused agent for writing, reviewing, and debugging.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'coding',
        archetype: 'coder',
        system_prompt: 'You are an expert programmer. Help users write clean, efficient code. Explain your reasoning and follow best practices.'
      },
      {
        name: 'Researcher',
        category: 'Research',
        description: 'Analytical agent for complex topics and synthesis.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'research',
        archetype: 'researcher',
        system_prompt: 'You are a research analyst. Break down complex topics with clear structure and concise findings.'
      },
      {
        name: 'Writer',
        category: 'Writing',
        description: 'Creative drafting, editing, and tone adaptation.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'full',
        archetype: 'writer',
        system_prompt: 'You are a skilled writer and editor. Help users create polished content and offer constructive improvements.'
      },
      {
        name: 'Data Analyst',
        category: 'Development',
        description: 'Data analysis, SQL/Python queries, and interpretation.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'coding',
        archetype: 'analyst',
        system_prompt: 'You are a data analysis expert. Help with dataset analysis, SQL/Python queries, and actionable interpretation.'
      },
      {
        name: 'DevOps Engineer',
        category: 'Development',
        description: 'CI/CD, infra, containers, and deployment reliability.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'automation',
        archetype: 'devops',
        system_prompt: 'You are a DevOps engineer. Help with CI/CD pipelines, Docker, infrastructure, deployment, and reliability.'
      },
      {
        name: 'Customer Support',
        category: 'Business',
        description: 'Empathetic and professional issue resolution.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'messaging',
        archetype: 'support',
        system_prompt: 'You are a professional support agent. Be empathetic, concise, and solution-oriented.'
      },
      {
        name: 'Tutor',
        category: 'General',
        description: 'Step-by-step explanations adapted to learner level.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'full',
        archetype: 'assistant',
        system_prompt: 'You are a patient tutor. Explain step-by-step, check understanding, and adapt to learner pace.'
      },
      {
        name: 'API Designer',
        category: 'Development',
        description: 'REST design, schema consistency, and versioning.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'coding',
        archetype: 'coder',
        system_prompt: 'You are an API design expert. Design clean RESTful APIs with robust schemas, error handling, and versioning.'
      },
      {
        name: 'Meeting Notes',
        category: 'Business',
        description: 'Summaries with decisions and action items.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'minimal',
        archetype: 'analyst',
        system_prompt: 'You summarize meetings into key decisions, action items, highlights, and follow-up questions.'
      },
      {
        name: 'Other',
        category: 'General',
        description: 'Specify a special purpose.',
        provider: 'groq',
        model: 'llama-3.3-70b-versatile',
        profile: 'full',
        archetype: 'custom',
        system_prompt: '',
        is_other: true
      }
    ],
    freshInitPersonalityCards: [
      {
        id: 'none',
        name: 'None',
        description: 'Use role defaults.',
        system_suffix: '',
        vibe: '',
      },
      {
        id: 'strategist',
        name: 'Strategist',
        description: 'Plan-first, structured, high-leverage.',
        system_suffix: 'Personality directive: be strategic, structured, and ROI-first. Offer concise plans and tradeoffs before action.',
        vibe: 'strategic',
      },
      {
        id: 'operator',
        name: 'Operator',
        description: 'Execution-focused, decisive, practical.',
        system_suffix: 'Personality directive: prioritize practical execution, clear next steps, and finish-line ownership.',
        vibe: 'operator',
      },
      {
        id: 'teacher',
        name: 'Teacher',
        description: 'Clear explanations, coaching-oriented.',
        system_suffix: 'Personality directive: teach with short, clear explanations and check understanding when useful.',
        vibe: 'mentor',
      },
      {
        id: 'creative',
        name: 'Creative',
        description: 'Idea-rich, exploratory, inventive.',
        system_suffix: 'Personality directive: be inventive and exploratory while staying concrete and useful.',
        vibe: 'creative',
      },
      {
        id: 'skeptic',
        name: 'Skeptic',
        description: 'Challenge assumptions, find weak points.',
        system_suffix: 'Personality directive: challenge assumptions, identify risks early, and pressure-test plans.',
        vibe: 'analytical',
      }
    ],
    freshInitLifespanCards: [
      {
        id: 'permanent',
        name: 'Permanent',
        description: 'No auto-expiry. Stays active until manual archive/revoke.',
        termination_condition: 'manual',
        indefinite: true,
        expiry_seconds: null,
      },
      {
        id: 'task',
        name: 'Until task is finished',
        description: 'Ends only when task is marked complete.',
        termination_condition: 'task_complete',
        indefinite: true,
        expiry_seconds: null,
      },
      {
        id: '1h',
        name: '1 hour',
        description: 'Auto-expires in 1 hour.',
        termination_condition: 'task_or_timeout',
        indefinite: false,
        expiry_seconds: 60 * 60,
      },
      {
        id: '1d',
        name: '1 day',
        description: 'Auto-expires in 1 day.',
        termination_condition: 'task_or_timeout',
        indefinite: false,
        expiry_seconds: 24 * 60 * 60,
      },
      {
        id: '1w',
        name: '1 week',
        description: 'Auto-expires in 1 week.',
        termination_condition: 'task_or_timeout',
        indefinite: false,
        expiry_seconds: 7 * 24 * 60 * 60,
      },
      {
        id: '1m',
        name: '1 month',
        description: 'Auto-expires in 1 month.',
        termination_condition: 'task_or_timeout',
        indefinite: false,
        expiry_seconds: 30 * 24 * 60 * 60,
      }
    ],
    freshInitVibeCards: [
      {
        id: 'none',
        name: 'None',
        description: 'Use role defaults.',
        system_suffix: '',
      },
      {
        id: 'friendly',
        name: 'Friendly',
        description: 'Warm, approachable, and collaborative.',
        system_suffix: 'Vibe directive: keep the tone warm, approachable, and encouraging while staying concise.',
      },
